### ISSUE TITLE
Broken Build

### ISSUE THREAD

**Issue by AdrieanKhisbe** [ecukes/espuds#28]
Currently build fails on `emacs-23.4-bin` because the function `split-window-right` didn't exist back then.

This occur in the `when-i-delete-other-windows` test.

Two options:
- either mock, port the function
- adapt the test not to use this function
- allow failure on  `emacs-23.4-bin`

**Comment by rejeep** [comment]
You forgot the option "I don't give a fuck about Emacs 23" https://github.com/ecukes/espuds/commit/8483b9afb943dba0b01eac2d616a09519cc722ea :smile:

**Comment by AdrieanKhisbe** [comment]
Nope, I just didn't said it out loud . ^^
haha
