### ISSUE TITLE
Two calls to "When I turn on minor-mode" turns the mode off

### ISSUE THREAD

**Issue by davidshepherd7** [ecukes/espuds#35]
It seems that using `When I turn on ...-mode` twice results in the mode being turned off. It only seems to happen with minor modes. I really don't understand why this is happening, the step definition looks like it should unconditionally enable the mode!

This issue means that if you put such a statement in the `Background:` the mode is only enabled for every other test.

Here's an example:

Step definition file:

    (Then "^abbrev-mode is on$"
        (lambda ()
            (cl-assert abbrev-mode)
            ))

Feature file:

    Feature: The ecukes tests work
      Background:
        When I turn on abbrev-mode

      Scenario: The mode is enabled correctly
        Then abbrev-mode is on

      Scenario: The mode is not just being toggled
        Then abbrev-mode is on

I've also managed to reproduce it in the espuds ert tests, I'll send a pull request now.

**Comment by rejeep** [comment]
Closing in favour of https://github.com/ecukes/espuds/pull/36
