### ISSUE TITLE
How to turn off a mode?

### ISSUE THREAD

**Issue by Trevoke** [ecukes/espuds#38]
I'm new to a lot of this, so my guess based on is that in emacs:

- `C-u M-x my-mode` unconditionally enables the mode
- `C-u -1 M-x my-mode` unconditionally disables the mode?

I'm trying to define a helper to turn off the mode, but I don't know how to add the universal arguments to the vector: `[?\C-u \- 1 ?\M-x]` does not seem to work, and I don't quite know what changes I need to make.

I was also surprised that this didn't exist as a step in espuds :)

**Comment by rejeep** [comment]
> I was also surprised that this didn't exist as a step in espuds :)

I'm trying to only add what people are using and this has never come up as a request, so therefore it's not added. But I agree that it can be useful, so I'm not apposed to adding it.

I would implement it as with the "turn on mode" step: https://github.com/ecukes/espuds/blob/master/espuds.el#L323

A good way of finding out the vector for a macro is to do the following:

```
M-x kmacro-start-macro # start recording macro
C-u -1 my-mode RET # enter key sequence
M-x name-last-kbd-macro foo RET # name last key board macro
M-x insert-kbd-macro RET foo RET # insert keyboard macro
```

**Comment by rejeep** [comment]
Closing via https://github.com/ecukes/espuds/pull/40
