### ISSUE TITLE
Should we add `RET` to the vector for turning on a mode?

### ISSUE THREAD

**Issue by Trevoke** [ecukes/espuds#39]
I'm working on a mode where the enter key can trigger some behavior, and I would like to replicate a particular behavior that occurs when manually turning on the minor mode (that is, basically, `M-x mode RET`).

Locally I was able to modify the espuds-provided step definition like so to reproduce the desired defect in my code:

```emacs-lisp
(When "^I turn on \\(.+\\)$"
  "Turns on some mode."
  (lambda (mode)
    (let ((v (vconcat [?\C-u ?\M-x] (string-to-vector mode) [?\C-m])))
(execute-kbd-macro v))))
```

Do you think this is an acceptable modification of this step, or might it be better to create a new one like "When I manually turn on foo-mode" ?

**Comment by rejeep** [comment]
I don't want to change this in espuds as many projects using espuds would be affected. I think it's better you add this step to your projects step-definitions file.
