### ISSUE TITLE
"Then I should see" ignores indentation and whitespace

### ISSUE THREAD

**Issue by BitPuffin** [ecukes/espuds#44]
This really tripped me up because that's exactly what I was testing for:

I was testing a function that transforms:

```boo
if foo():
  bar()
```

into

```boo
bar() if foo()
```

and that it does so with the correct indentation.

Turns out that as long as the non-whitespace characters showed up in the right order the test would pass. Even if I tested for:

```
  Scenario: Toggle Multi Line to Single Line
    When I insert:
    """
    if foo():
      bar()
    """
    And I press "C-p"
    When I call "boo-toggle-single-line-control-flow"
    Then I should see: 
    """
bar() 










if


 foo()




"""
```

Which makes it really useless for this usecase.

**Comment by BitPuffin** [comment]
Not so sure anymore that this is espuds fault but rather something extremely weird with ecukes itself.

Since I tried to work around this problem by creating my own 

``` elisp
(Then "^I should see exactly\\(?: \"\\(.+\\)\"\\|:\\)$"
 ; ....
)
```

But then I got the same behaviour and I was like WTF.

And then I eventually ended up discovering that:

``` elisp
(Then "^I should see exactly\\(?: \"\\(.+\\)\"\\|:\\)$"
  (lambda (expected)
    (cl-assert nil nil "lol")))
```
passes (?????????)

But

``` elisp
(Then "^I should see exactly\\(?: \"\\(.+\\)\"\\|:\\)$"
  (lambda (expected)
    (error "lol")))
```
Does not.

Fun times.

Anyway espuds uses cl-assert so ¯\_(ツ)_/¯

**Comment by davidshepherd7** [comment]
Yeah in emacs 25 the behaviour of `cl-assert` changed in a way that breaks ecukes' error reporting :disappointed:. I'm looking into it, but I'm not the original author so it's tough going (the original author, Rejeep, is busy with other stuff these days).

For now a workaround is to override the broken version of `cl-assert` with the old code using [this snippet](https://github.com/davidshepherd7/espuds/commit/07a479a8ecb39e5f0b7342f7951257572809bcba).
