### ISSUE TITLE
When I press "C-return"       C- must prefix a single character, not return

### ISSUE THREAD

**Issue by RCoeurjoly** [ecukes/espuds#48]
C-return is a valid key-binding in Emacs org mode, meaning create new heading.

When creating a scenario using this key binding, the following error pops up:

> When I press "C-return"
      C- must prefix a single character, not return

**Comment by iquiw** [comment]
Could you try `<C-return>` instead? (I didn't try actually...)

**Comment by RCoeurjoly** [comment]
When I try <C-return>:

> <C.return> is undefined

**Comment by iquiw** [comment]
Not `.`, but `-`

**Comment by RCoeurjoly** [comment]
I did write `<C-return>`

The complete log is as follows:

> 
> <C.return> is undefined
> 
>   Scenario: autocomplete funcion
>     When I place the cursor after "match = re"
>     And I type ".de"
>     And I press "RET"
>     Then I should see:
>       """
>       import re
>       match = re.DEBUG
>       """
>       Expected
>       import re
>       match = re.DEBUG
>       to be part of:
>       import re
>       match = re.de
>       
> 
>   Scenario: Create new heading
>     When I press `<C-return>`
>     Then I should see:
>       """
>       *
>       """
>       Expected
>       *
>       to be part of:
>       
> 
> 3 scenarios (2 failed, 1 passed)
> 15 steps (2 failed, 0 skipped, 13 passed)
> 
>

**Comment by iquiw** [comment]
`"<C-return>"`

Tried and worked as expected.
https://github.com/iquiw/test-ecukes

**Comment by RCoeurjoly** [comment]
Weird... It seems that I wasn't activating org-mode.

Once it is turned on, the test works.

Thanks anyway.

[https://github.com/RCoeurjoly/dotfiles/tree/master/spacemacs/.spacemacs.d](url)
